insert into hotel_info  (address, ward, district, city, country, hotel_name, hotel_star_level, hotel_status, hotel_type)
values  ('4272 Swallow Park', 'a', 'b', 'Nansheng', 'China', 'Youspan', 3, 'ACCEPTED', 'Apartment'),
        ('998 Stoughton Point', 'a', 'b', 'Oetua', 'Indonesia', 'Skinix', 3, 'ACCEPTED', 'Resort'),
        ('026 1st Junction', 'a', 'b', 'Hirara', 'Japan', 'Eidel', 1, 'PENDING', 'Apartment'),
        ('91 Coolidge Pass', 'a', 'b', 'Pentaplátano', 'Greece', 'Kimia', 1, 'ACCEPTED', 'Apartment'),
        ('1 Hooker Way', 'a', 'b', 'Sopron', 'Hungary', 'Blogtag', 1, 'PENDING', 'Airport Hotel'),
        ('5 Waxwing Lane', 'a', 'b', 'Salavan', 'Laos', 'Centidel', 4, 'PENDING', 'Airport Hotel'),
        ('10836 Hazelcrest Street', 'a', 'b', 'Nejo', 'Ethiopia', 'Jamia', 2, 'DENIED', 'Hotel'),
        ('1 Clarendon Trail', 'a', 'b', 'Sobo', 'Indonesia', 'Gigashots', 5, 'ACCEPTED', 'Hotel'),
        ('6 Kim Alley', 'a', 'b', 'Jintao', 'China', 'Wikizz', 5, 'DENIED', 'Airport Hotel'),
        ('2926 Beilfuss Way', 'a', 'b', 'Det Udom', 'Thailand', 'Fanoodle', 3, 'PENDING', 'Apartment'),
        ('998 Union Crossing', 'a', 'b', 'San Pedro', 'Belize', 'Wordpedia', 2, 'PENDING', 'Motel'),
        ('3 Crowley Terrace', 'a', 'b', 'Sóc Sơn', 'Vietnam', 'Skivee', 1, 'PENDING', 'Motel'),
        ('73 Clyde Gallagher Trail', 'a', 'b', 'Sewon', 'Indonesia', 'Jayo', 1, 'PENDING', 'Hotel'),
        ('6 Crest Line Parkway', 'a', 'b', 'Três Lagoas', 'Brazil', 'Vidoo', 5, 'PENDING', 'Resort'),
        ('26 Farragut Parkway', 'a', 'b', 'Vitali', 'Philippines', 'Gabtype', 1, 'DENIED', 'Apartment'),
        ('946 Autumn Leaf Pass', 'a', 'b', 'Sinarharapan', 'Indonesia', 'Zoonder', 2, 'PENDING', 'Resort'),
        ('1756 Pleasure Avenue', 'a', 'b', 'Hacienda La Calera', 'Chile', 'Teklist', 3, 'PENDING', 'Hotel'),
        ('932 Comanche Road', 'a', 'b', 'Khulo', 'Georgia', 'Aivee', 3, 'DENIED', 'Hotel'),
        ('933 Forest Run Trail', 'a', 'b', 'Madrid', 'Spain', 'Oba', 2, 'PENDING', 'Hotel'),
        ('697 Nevada Circle', 'a', 'b', 'Radišići', 'Bosnia and Herzegovina', 'Meeveo', 5, 'DENIED', 'Apartment');
